site_name: MicroPythonOS Documentation
site_url: https://docs.micropythonos.com
repo_url: https://github.com/MicroPythonOS/MicroPythonOS
use_directory_urls: true
theme:
  name: material
  logo: https://micropythonos.com/images/MicroPythonOS-logo-white(alpha)-long.svg
  palette:
    # Light theme
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark theme
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.copy
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
  custom_dir: docs/overrides
extra_css:
  - stylesheets/extra.css
markdown_extensions:
    - markdown_include.include:
        base_path: docs
nav:
  - Home: index.md
  - Overview: overview.md
  - Getting Started:
      - Overview: getting-started/index.md
      - Installation: getting-started/installation.md
      - Supported Hardware: getting-started/supported-hardware.md
  - Apps:
      - Overview: apps/index.md
      - Built-in Apps: apps/built-in-apps.md
      - App Store: apps/appstore.md
      - Creating Apps: apps/creating-apps.md
      - Bundling Apps: apps/bundling-apps.md
  - Frameworks:
      - AudioFlinger: frameworks/audioflinger.md
      - BatteryManager: frameworks/battery-manager.md
      - BuildInfo: frameworks/build-info.md
      - ConnectivityManager: frameworks/connectivity-manager.md
      - DeviceInfo: frameworks/device-info.md
      - DisplayMetrics: frameworks/display-metrics.md
      - DownloadManager: frameworks/download-manager.md
      - InputManager: frameworks/input-manager.md
      - LightsManager: frameworks/lights-manager.md
      - Preferences: frameworks/preferences.md
      - SensorManager: frameworks/sensor-manager.md
      - SettingActivity: frameworks/setting-activity.md
      - SettingsActivity: frameworks/settings-activity.md
      - TaskManager: frameworks/task-manager.md
      - TimeZone: frameworks/time-zone.md
      - WidgetAnimator: frameworks/widget-animator.md
      - WifiService: frameworks/wifi-service.md
  - Architecture:
      - Overview: architecture/index.md
      - Architecture Overview: architecture/overview.md
      - Frameworks: architecture/frameworks.md
      - System Components: architecture/system-components.md
      - Filesystem Layout: architecture/filesystem.md
  - OS Development:
      - Overview: os-development/index.md
      - Running on Desktop: os-development/running-on-desktop.md
      - On Linux: os-development/linux.md
      - On MacOS: os-development/macos.md
      - On Windows: os-development/windows.md
      - Installing on ESP32: os-development/installing-on-esp32.md
      - Porting Guide: os-development/porting-guide.md
  - Other:
      - Release Process: other/release-checklist.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MicroPythonOS
    - icon: fontawesome/solid/comments
      link: https://chat.micropythonos.com
    - icon: fontawesome/solid/envelope
      link: mailto:info@micropythonos.com
