site_name: MicroPythonOS Documentation
site_url: https://docs.micropythonos.com
repo_url: https://github.com/MicroPythonOS/MicroPythonOS
use_directory_urls: true
theme:
  name: material
  palette:
    # Light theme
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark theme
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.copy
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
  custom_dir: docs/overrides
extra_css:
  - stylesheets/extra.css
markdown_extensions:
    - markdown_include.include:
        base_path: docs
nav:
  - Home: index.md
  - Overview: overview.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Supported Hardware: getting-started/supported-hardware.md
  - Apps:
      - Overview: apps/index.md
      - Built-in Apps: apps/built-in-apps.md
      - App Store: apps/appstore.md
      - Creating Apps: apps/creating-apps.md
      - Bundling Apps: apps/bundling-apps.md
  - Frameworks:
      - Preferences: frameworks/preferences.md
      - TaskManager: frameworks/task-manager.md
      - DownloadManager: frameworks/download-manager.md
      - SensorManager: frameworks/sensor-manager.md
      - AudioFlinger: frameworks/audioflinger.md
      - LightsManager: frameworks/lights-manager.md
  - Architecture:
      - Overview: architecture/overview.md
      - System Components: architecture/system-components.md
      - Filesystem Layout: architecture/filesystem.md
  - OS Development:
      - On Linux: os-development/linux.md
      - On MacOS: os-development/macos.md
      - On Windows: os-development/windows.md
      - Installing on ESP32: os-development/installing-on-esp32.md
      - Porting Guide: os-development/porting-guide.md
  - Other:
      - Release Process: other/release-checklist.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MicroPythonOS
    - icon: fontawesome/solid/comments
      link: https://chat.micropythonos.com
    - icon: fontawesome/solid/envelope
      link: mailto:info@micropythonos.com
